### ISSUE TITLE
Wrong Coords

### ISSUE THREAD

**Issue by Kongduino** [mrpatrick1991/meshtastic_linkplanner#1]
When I click on anything that's east of the Greenwich meridian I get incorrect values. For example, if I click on HK airport, in the 22/14 range, I get 22/-246, which is incorrect.

![Untitled 4](https://github.com/user-attachments/assets/056ee228-6ba6-457b-8964-fdc2a1c7da68)

**Comment by mrpatrick1991** [comment]
Yes, confirmed. I'll figure out where this is and fix it. Thanks!

**Comment by Nasticator** [comment]
To add to this if you scroll the map east it works fine it's when you go west from origin it gives negative numbers

**Comment by mrpatrick1991** [comment]
Appears fixed.

**Comment by Kongduino** [comment]
Indeed appears to work properly now!
