### ISSUE TITLE
[Bug] Map Scrolling & visible tiles

### ISSUE THREAD

**Issue by OE3JGW** [mrpatrick1991/meshtastic_linkplanner#5]
After a pin has been set and the model ran, you sometimes cannot see the tiles (result). 

**Reason / Cause:**
If youre using the world map to scroll to the left to find your country, youre moving away from the "world" the linkplanner is using. 

**Workaround:**
- scroll how you want to scroll
- set your pin
- run the model
- zoom out, then you will see another blue place, if you zoom it you will find the tiles/results

**Also see screenshot:**
![screenshot](https://github.com/user-attachments/assets/9022210c-51b3-4bec-a251-a5fda6dd5ee6)

**edit:**
- im using chrome and i also disabled all plugins to test it

**Comment by mrpatrick1991** [comment]
Thanks for the detailed report, I was able to reproduce. For now we will use https://github.com/mrpatrick1991/meshtastic_linkplanner/pull/3 which restricts the map to one view of the world. 

I've updated the hosted version. Please force-refresh the page (ignoring cache). I'll close this for now.
