### ISSUE TITLE
[Feature Request] Add 433mhz Meshtastic (HAM)

### ISSUE THREAD

**Issue by OE3JGW** [mrpatrick1991/meshtastic_linkplanner#6]
Awesome tool, thanks for sharing!

I dont use the 433mhz meshtastic, but i can see why it might be interesting to include it for some people as its part of meshtastic, therefore im requesting it :)

**Comment by mrpatrick1991** [comment]
should be fixed in https://github.com/mrpatrick1991/meshtastic_linkplanner/pull/7

I'll get the hosted version updated shortly. 

(feel free to re-open if I've missed something.)
